import:
  # - ~/.config/alacritty/visual/colors/arc.yml
  # - ~/.config/alacritty/visual/colors/code.yml
  # - ~/.config/alacritty/visual/colors/ephemeral.yml
  # - ~/.config/alacritty/visual/colors/fox.yml
  # - ~/.config/alacritty/visual/colors/insomnia.yml
  # - ~/.config/alacritty/visual/colors/lovelace.yml
  # - ~/.config/alacritty/visual/colors/neon.yml
  - ~/.config/alacritty/visual/colors/nightfox.yml
  # - ~/.config/alacritty/visual/colors/skyfall.yml
  # - ~/.config/alacritty/visual/colors/tomorrow_night.yml

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Bell
#
# The bell is rung every time the BEL control character is received.
bell:
  # Duration of the visual bell flash. A `duration` of `0` will disable the
  # visual bell animation.
  duration: 0

